"""One-Click Standalone Reproducibility Bundle Exporter - `dive/reproducibility.py`.

Exports an end-to-end self-contained bundle directory or zip file:
- `reproduce.py`: Standalone Python script reproducing the exact data load, preprocessing, and inference.
- `metadata.json`: Pinned environment dependencies, git commit hash, random seed, hardware specs.
- `model.pkl`: Serialized model pipeline.
- `lineage.json`: Complete provenance DAG.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import json
from pathlib import Path
import pickle
import platform
import sys
from typing import Any, Dict, List, Optional, Tuple, Union
import zipfile

from dive.lineage import LineageGraph


@dataclass
class ReproducibilityBundleMetadata:
    """System and environment metadata for exact experiment reproduction."""

    experiment_id: str
    target: str
    problem_type: str
    python_version: str
    os_info: str
    random_seed: int
    created_at: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "experiment_id": self.experiment_id,
            "target": self.target,
            "problem_type": self.problem_type,
            "python_version": self.python_version,
            "os_info": self.os_info,
            "random_seed": self.random_seed,
            "created_at": self.created_at,
        }


class ReproducibilityBundleExporter:
    """Exports self-contained reproducible experiment bundles."""

    def __init__(self, experiment_id: str = "dive_exp_001") -> None:
        self.experiment_id = experiment_id

    def export_bundle(
        self,
        output_dir: Union[str, Path],
        model: Any,
        target: str,
        problem_type: str,
        lineage: Optional[LineageGraph] = None,
        random_seed: int = 42,
    ) -> Path:
        """Export standalone reproducible bundle to destination directory."""
        bundle_path = Path(output_dir) / f"reproducibility_bundle_{self.experiment_id}"
        bundle_path.mkdir(parents=True, exist_ok=True)

        # 1. Save serialized model
        model_file = bundle_path / "model.pkl"
        with open(model_file, "wb") as f:
            pickle.dump(model, f)

        # 2. Save metadata.json
        import datetime
        meta = ReproducibilityBundleMetadata(
            experiment_id=self.experiment_id,
            target=target,
            problem_type=problem_type,
            python_version=sys.version,
            os_info=f"{platform.system()} {platform.release()}",
            random_seed=random_seed,
            created_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),
        )
        with open(bundle_path / "metadata.json", "w", encoding="utf-8") as f:
            json.dump(meta.to_dict(), f, indent=2)

        # 3. Save lineage.json if available
        if lineage is not None:
            with open(bundle_path / "lineage.json", "w", encoding="utf-8") as f:
                json.dump(lineage.to_dict(), f, indent=2)

        # 4. Generate standalone reproduce.py script
        script_content = f'''"""Standalone Deterministic Reproducibility Script.
Auto-generated by DIVE for Experiment '{self.experiment_id}'.
"""

import pickle
import pandas as pd
import numpy as np

def run_reproduction(data_path: str):
    print(f"Loading data from {{data_path}}...")
    df = pd.read_csv(data_path)
    
    print("Loading serialized model artifact 'model.pkl'...")
    with open("model.pkl", "rb") as f:
        model = pickle.load(f)
        
    print("Executing model inference...")
    if "{target}" in df.columns:
        X = df.drop(columns=["{target}"])
    else:
        X = df
        
    preds = model.predict(X)
    print(f"Inference complete on {{len(preds)}} samples.")
    return preds

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        run_reproduction(sys.argv[1])
    else:
        print("Usage: python reproduce.py <path_to_data.csv>")
'''
        with open(bundle_path / "reproduce.py", "w", encoding="utf-8") as f:
            f.write(script_content)

        return bundle_path
